import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

const futura = localFont({
  src: '../../public/fonts/Futura-Bold.woff2',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={futura.className}>{children}</body>
    </html>
  );
}
